You are given a string 'STR' containing lowercase English letters from a to z
inclusive. Your task is to find all non-empty possible subsequences of 'STR.
A Subsequence of a string is the one which is generated by deleting O or more
letters from the string and keeping the rest of the letters in the same order.
Sample Input 1:
1 
abc
Sample Output 1:
a ab abc ac b bc c
Explanation of sample input 1:
All possible subsequences of abc are :  
“a” , “b” , “c” , “ab” , “bc” , “ac”, “abc”
Sample Input 2:
1
bbb
Sample Output 2:
b b b bb bb bb bbb


Answer:
#include <bits/stdc++.h> 
void generateSubsequences(string str, int index, string current, vector<string>& result) {
    if (index == str.length()) {
        if (!current.empty()) {
            result.push_back(current);
        }
        return;
    }

    generateSubsequences(str, index + 1, current + str[index], result);

    generateSubsequences(str, index + 1, current, result);
}
vector<string> subsequences(string str){
	vector<string> result;
    generateSubsequences(str, 0, "", result);
    return result;
	
	
	
}
